// Mocks generated by Mockito 5.4.3 from annotations
// in movid/test/helpers/global_test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:convert' as _i25;
import 'dart:typed_data' as _i24;

import 'package:dartz/dartz.dart' as _i5;
import 'package:hive/hive.dart' as _i10;
import 'package:hive/src/box/default_compaction_strategy.dart' as _i23;
import 'package:hive/src/box/default_key_comparator.dart' as _i22;
import 'package:http/http.dart' as _i11;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:movid/core/errors/failure.dart' as _i18;
import 'package:movid/core/network/network_connection.dart' as _i7;
import 'package:movid/features/movies/data/data_sources/movie_local_data_source.dart'
    as _i15;
import 'package:movid/features/movies/data/data_sources/movie_remote_data_source.dart'
    as _i13;
import 'package:movid/features/movies/data/models/media_image_model.dart'
    as _i3;
import 'package:movid/features/movies/data/models/movie_detail_model.dart'
    as _i2;
import 'package:movid/features/movies/data/models/movie_model.dart' as _i14;
import 'package:movid/features/series/data/data_sources/tv_series_remote_data_source_impl.dart'
    as _i6;
import 'package:movid/features/series/data/model/media_image_model.dart' as _i9;
import 'package:movid/features/series/data/repository/series_repository_impl.dart'
    as _i21;
import 'package:movid/features/series/domain/entites/season.dart' as _i20;
import 'package:movid/features/series/domain/entites/series.dart' as _i19;
import 'package:movid/features/series/domain/entites/series_detail.dart' as _i8;
import 'package:movid/features/series/domain/repository/series_repository.dart'
    as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieDetailModel_0 extends _i1.SmartFake
    implements _i2.MovieDetailModel {
  _FakeMovieDetailModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMediaImageModel_1 extends _i1.SmartFake
    implements _i3.MediaImageModel {
  _FakeMediaImageModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressCheckResult_3 extends _i1.SmartFake
    implements _i4.AddressCheckResult {
  _FakeAddressCheckResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_4<L, R> extends _i1.SmartFake implements _i5.Either<L, R> {
  _FakeEither_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesRemoteDataSource_5 extends _i1.SmartFake
    implements _i6.TvSeriesRemoteDataSource {
  _FakeTvSeriesRemoteDataSource_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkConnection_6 extends _i1.SmartFake
    implements _i7.NetworkConnection {
  _FakeNetworkConnection_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeriesDetail_7 extends _i1.SmartFake implements _i8.SeriesDetail {
  _FakeSeriesDetail_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMediaImageModel_8 extends _i1.SmartFake
    implements _i9.MediaImageModel {
  _FakeMediaImageModel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_9<E1> extends _i1.SmartFake implements _i10.Box<E1> {
  _FakeBox_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLazyBox_10<E1> extends _i1.SmartFake implements _i10.LazyBox<E1> {
  _FakeLazyBox_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_11 extends _i1.SmartFake implements _i11.Response {
  _FakeResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_12 extends _i1.SmartFake
    implements _i11.StreamedResponse {
  _FakeStreamedResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkConnection extends _i1.Mock implements _i7.NetworkConnection {
  MockNetworkConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<bool> get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i13.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i14.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
        ),
        returnValue:
            _i12.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i12.Future<List<_i14.MovieModel>>);

  @override
  _i12.Future<List<_i14.MovieModel>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i12.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i12.Future<List<_i14.MovieModel>>);

  @override
  _i12.Future<List<_i14.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i12.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i12.Future<List<_i14.MovieModel>>);

  @override
  _i12.Future<_i2.MovieDetailModel> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue:
            _i12.Future<_i2.MovieDetailModel>.value(_FakeMovieDetailModel_0(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i12.Future<_i2.MovieDetailModel>);

  @override
  _i12.Future<List<_i14.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [id],
        ),
        returnValue:
            _i12.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i12.Future<List<_i14.MovieModel>>);

  @override
  _i12.Future<_i3.MediaImageModel> getMovieImages(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieImages,
          [id],
        ),
        returnValue:
            _i12.Future<_i3.MediaImageModel>.value(_FakeMediaImageModel_1(
          this,
          Invocation.method(
            #getMovieImages,
            [id],
          ),
        )),
      ) as _i12.Future<_i3.MediaImageModel>);

  @override
  _i12.Future<List<_i14.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i12.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i12.Future<List<_i14.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i15.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<String> saveWatchlist(_i2.MovieDetailModel? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [movie],
        ),
        returnValue: _i12.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [movie],
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<String> removeWatchlist(_i2.MovieDetailModel? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i12.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<bool> hasMovie(int? id) => (super.noSuchMethod(
        Invocation.method(
          #hasMovie,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<List<_i14.MovieModel>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue:
            _i12.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i12.Future<List<_i14.MovieModel>>);
}

/// A class which mocks [InternetConnectionChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectionChecker extends _i1.Mock
    implements _i4.InternetConnectionChecker {
  MockInternetConnectionChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get checkInterval => (super.noSuchMethod(
        Invocation.getter(#checkInterval),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#checkInterval),
        ),
      ) as Duration);

  @override
  Duration get checkTimeout => (super.noSuchMethod(
        Invocation.getter(#checkTimeout),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#checkTimeout),
        ),
      ) as Duration);

  @override
  List<_i4.AddressCheckOptions> get addresses => (super.noSuchMethod(
        Invocation.getter(#addresses),
        returnValue: <_i4.AddressCheckOptions>[],
      ) as List<_i4.AddressCheckOptions>);

  @override
  set addresses(List<_i4.AddressCheckOptions>? value) => super.noSuchMethod(
        Invocation.setter(
          #addresses,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<bool> get hasConnection => (super.noSuchMethod(
        Invocation.getter(#hasConnection),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<_i4.InternetConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatus),
        returnValue: _i12.Future<_i4.InternetConnectionStatus>.value(
            _i4.InternetConnectionStatus.connected),
      ) as _i12.Future<_i4.InternetConnectionStatus>);

  @override
  _i12.Stream<_i4.InternetConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
        Invocation.getter(#onStatusChange),
        returnValue: _i12.Stream<_i4.InternetConnectionStatus>.empty(),
      ) as _i12.Stream<_i4.InternetConnectionStatus>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isActivelyChecking => (super.noSuchMethod(
        Invocation.getter(#isActivelyChecking),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<_i4.AddressCheckResult> isHostReachable(
          _i4.AddressCheckOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #isHostReachable,
          [options],
        ),
        returnValue:
            _i12.Future<_i4.AddressCheckResult>.value(_FakeAddressCheckResult_3(
          this,
          Invocation.method(
            #isHostReachable,
            [options],
          ),
        )),
      ) as _i12.Future<_i4.AddressCheckResult>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i17.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>> getOnAirTvSeries(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnAirTvSeries,
          [page],
        ),
        returnValue:
            _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
          this,
          Invocation.method(
            #getOnAirTvSeries,
            [page],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getPopularTvSeries,
              [],
            ),
            returnValue: _i12
                .Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
              this,
              Invocation.method(
                #getPopularTvSeries,
                [],
              ),
            )),
          ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTvSeries,
              [],
            ),
            returnValue: _i12
                .Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
              this,
              Invocation.method(
                #getTopRatedTvSeries,
                [],
              ),
            )),
          ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, _i8.SeriesDetail>> getDetailTvSeries(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailTvSeries,
          [id],
        ),
        returnValue:
            _i12.Future<_i5.Either<_i18.Failure, _i8.SeriesDetail>>.value(
                _FakeEither_4<_i18.Failure, _i8.SeriesDetail>(
          this,
          Invocation.method(
            #getDetailTvSeries,
            [id],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, _i8.SeriesDetail>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>
      getRecommendedTvSeries(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getRecommendedTvSeries,
              [id],
            ),
            returnValue: _i12
                .Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
              this,
              Invocation.method(
                #getRecommendedTvSeries,
                [id],
              ),
            )),
          ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, _i20.Season>> getTvSeriesSeasons() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesSeasons,
          [],
        ),
        returnValue: _i12.Future<_i5.Either<_i18.Failure, _i20.Season>>.value(
            _FakeEither_4<_i18.Failure, _i20.Season>(
          this,
          Invocation.method(
            #getTvSeriesSeasons,
            [],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, _i20.Season>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>> searchTvSeries(
          String? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [data],
        ),
        returnValue:
            _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
          this,
          Invocation.method(
            #searchTvSeries,
            [data],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, _i9.MediaImageModel>> getSeriesImages(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeriesImages,
          [id],
        ),
        returnValue:
            _i12.Future<_i5.Either<_i18.Failure, _i9.MediaImageModel>>.value(
                _FakeEither_4<_i18.Failure, _i9.MediaImageModel>(
          this,
          Invocation.method(
            #getSeriesImages,
            [id],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, _i9.MediaImageModel>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>
      getWatchListTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getWatchListTvSeries,
              [],
            ),
            returnValue: _i12
                .Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
              this,
              Invocation.method(
                #getWatchListTvSeries,
                [],
              ),
            )),
          ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<bool> addSeriesToWatchList(_i19.TvSeries? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSeriesToWatchList,
          [series],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> removeWatchListSeries(_i19.TvSeries? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchListSeries,
          [series],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
}

/// A class which mocks [TvSeriesRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepositoryImpl extends _i1.Mock
    implements _i21.TvSeriesRepositoryImpl {
  MockTvSeriesRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvSeriesRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeTvSeriesRemoteDataSource_5(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i6.TvSeriesRemoteDataSource);

  @override
  _i7.NetworkConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeNetworkConnection_6(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i7.NetworkConnection);

  @override
  _i12.Future<bool> addSeriesToWatchList(_i19.TvSeries? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSeriesToWatchList,
          [series],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>
      getWatchListTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getWatchListTvSeries,
              [],
            ),
            returnValue: _i12
                .Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
              this,
              Invocation.method(
                #getWatchListTvSeries,
                [],
              ),
            )),
          ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<bool> removeWatchListSeries(_i19.TvSeries? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchListSeries,
          [series],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, _i8.SeriesDetail>> getDetailTvSeries(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailTvSeries,
          [id],
        ),
        returnValue:
            _i12.Future<_i5.Either<_i18.Failure, _i8.SeriesDetail>>.value(
                _FakeEither_4<_i18.Failure, _i8.SeriesDetail>(
          this,
          Invocation.method(
            #getDetailTvSeries,
            [id],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, _i8.SeriesDetail>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>> getOnAirTvSeries(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnAirTvSeries,
          [page],
        ),
        returnValue:
            _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
          this,
          Invocation.method(
            #getOnAirTvSeries,
            [page],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getPopularTvSeries,
              [],
            ),
            returnValue: _i12
                .Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
              this,
              Invocation.method(
                #getPopularTvSeries,
                [],
              ),
            )),
          ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>
      getRecommendedTvSeries(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getRecommendedTvSeries,
              [id],
            ),
            returnValue: _i12
                .Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
              this,
              Invocation.method(
                #getRecommendedTvSeries,
                [id],
              ),
            )),
          ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTvSeries,
              [],
            ),
            returnValue: _i12
                .Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
              this,
              Invocation.method(
                #getTopRatedTvSeries,
                [],
              ),
            )),
          ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, _i20.Season>> getTvSeriesSeasons() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesSeasons,
          [],
        ),
        returnValue: _i12.Future<_i5.Either<_i18.Failure, _i20.Season>>.value(
            _FakeEither_4<_i18.Failure, _i20.Season>(
          this,
          Invocation.method(
            #getTvSeriesSeasons,
            [],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, _i20.Season>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>> searchTvSeries(
          String? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [data],
        ),
        returnValue:
            _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>.value(
                _FakeEither_4<_i18.Failure, List<_i19.TvSeries>>(
          this,
          Invocation.method(
            #searchTvSeries,
            [data],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, List<_i19.TvSeries>>>);

  @override
  _i12.Future<_i5.Either<_i18.Failure, _i9.MediaImageModel>> getSeriesImages(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeriesImages,
          [id],
        ),
        returnValue:
            _i12.Future<_i5.Either<_i18.Failure, _i9.MediaImageModel>>.value(
                _FakeEither_4<_i18.Failure, _i9.MediaImageModel>(
          this,
          Invocation.method(
            #getSeriesImages,
            [id],
          ),
        )),
      ) as _i12.Future<_i5.Either<_i18.Failure, _i9.MediaImageModel>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i6.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i19.TvSeries>> getOnAirTvSeries(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnAirTvSeries,
          [page],
        ),
        returnValue: _i12.Future<List<_i19.TvSeries>>.value(<_i19.TvSeries>[]),
      ) as _i12.Future<List<_i19.TvSeries>>);

  @override
  _i12.Future<List<_i19.TvSeries>> getPopularTvSeries() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTvSeries,
          [],
        ),
        returnValue: _i12.Future<List<_i19.TvSeries>>.value(<_i19.TvSeries>[]),
      ) as _i12.Future<List<_i19.TvSeries>>);

  @override
  _i12.Future<List<_i19.TvSeries>> getTopRatedTvSeries() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvSeries,
          [],
        ),
        returnValue: _i12.Future<List<_i19.TvSeries>>.value(<_i19.TvSeries>[]),
      ) as _i12.Future<List<_i19.TvSeries>>);

  @override
  _i12.Future<_i8.SeriesDetail> getDetailTvSeries(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailTvSeries,
          [id],
        ),
        returnValue: _i12.Future<_i8.SeriesDetail>.value(_FakeSeriesDetail_7(
          this,
          Invocation.method(
            #getDetailTvSeries,
            [id],
          ),
        )),
      ) as _i12.Future<_i8.SeriesDetail>);

  @override
  _i12.Future<List<_i19.TvSeries>> getRecommendedTvSeries(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedTvSeries,
          [id],
        ),
        returnValue: _i12.Future<List<_i19.TvSeries>>.value(<_i19.TvSeries>[]),
      ) as _i12.Future<List<_i19.TvSeries>>);

  @override
  _i12.Future<List<_i19.TvSeries>> getTvSeriesSeasons() => (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesSeasons,
          [],
        ),
        returnValue: _i12.Future<List<_i19.TvSeries>>.value(<_i19.TvSeries>[]),
      ) as _i12.Future<List<_i19.TvSeries>>);

  @override
  _i12.Future<List<_i19.TvSeries>> searchTvSeries(String? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [data],
        ),
        returnValue: _i12.Future<List<_i19.TvSeries>>.value(<_i19.TvSeries>[]),
      ) as _i12.Future<List<_i19.TvSeries>>);

  @override
  _i12.Future<_i9.MediaImageModel> getSeriesImages(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeriesImages,
          [id],
        ),
        returnValue:
            _i12.Future<_i9.MediaImageModel>.value(_FakeMediaImageModel_8(
          this,
          Invocation.method(
            #getSeriesImages,
            [id],
          ),
        )),
      ) as _i12.Future<_i9.MediaImageModel>);

  @override
  _i12.Future<List<_i19.TvSeries>> getWatchListTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchListTvSeries,
          [],
        ),
        returnValue: _i12.Future<List<_i19.TvSeries>>.value(<_i19.TvSeries>[]),
      ) as _i12.Future<List<_i19.TvSeries>>);

  @override
  _i12.Future<bool> addSeriesToWatchList(_i19.TvSeries? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSeriesToWatchList,
          [series],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> removeWatchListSeries(_i19.TvSeries? series) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchListSeries,
          [series],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
}

/// A class which mocks [HiveInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveInterface extends _i1.Mock implements _i10.HiveInterface {
  MockHiveInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void init(
    String? path, {
    _i10.HiveStorageBackendPreference? backendPreference =
        _i10.HiveStorageBackendPreference.native,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #init,
          [path],
          {#backendPreference: backendPreference},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i10.Box<E>> openBox<E>(
    String? name, {
    _i10.HiveCipher? encryptionCipher,
    _i10.KeyComparator? keyComparator = _i22.defaultKeyComparator,
    _i10.CompactionStrategy? compactionStrategy =
        _i23.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    _i24.Uint8List? bytes,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [name],
          {
            #encryptionCipher: encryptionCipher,
            #keyComparator: keyComparator,
            #compactionStrategy: compactionStrategy,
            #crashRecovery: crashRecovery,
            #path: path,
            #bytes: bytes,
            #collection: collection,
            #encryptionKey: encryptionKey,
          },
        ),
        returnValue: _i12.Future<_i10.Box<E>>.value(_FakeBox_9<E>(
          this,
          Invocation.method(
            #openBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #bytes: bytes,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
      ) as _i12.Future<_i10.Box<E>>);

  @override
  _i12.Future<_i10.LazyBox<E>> openLazyBox<E>(
    String? name, {
    _i10.HiveCipher? encryptionCipher,
    _i10.KeyComparator? keyComparator = _i22.defaultKeyComparator,
    _i10.CompactionStrategy? compactionStrategy =
        _i23.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openLazyBox,
          [name],
          {
            #encryptionCipher: encryptionCipher,
            #keyComparator: keyComparator,
            #compactionStrategy: compactionStrategy,
            #crashRecovery: crashRecovery,
            #path: path,
            #collection: collection,
            #encryptionKey: encryptionKey,
          },
        ),
        returnValue: _i12.Future<_i10.LazyBox<E>>.value(_FakeLazyBox_10<E>(
          this,
          Invocation.method(
            #openLazyBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
      ) as _i12.Future<_i10.LazyBox<E>>);

  @override
  _i10.Box<E> box<E>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #box,
          [name],
        ),
        returnValue: _FakeBox_9<E>(
          this,
          Invocation.method(
            #box,
            [name],
          ),
        ),
      ) as _i10.Box<E>);

  @override
  _i10.LazyBox<E> lazyBox<E>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #lazyBox,
          [name],
        ),
        returnValue: _FakeLazyBox_10<E>(
          this,
          Invocation.method(
            #lazyBox,
            [name],
          ),
        ),
      ) as _i10.LazyBox<E>);

  @override
  bool isBoxOpen(String? name) => (super.noSuchMethod(
        Invocation.method(
          #isBoxOpen,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deleteBoxFromDisk(
    String? name, {
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBoxFromDisk,
          [name],
          {#path: path},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  List<int> generateSecureKey() => (super.noSuchMethod(
        Invocation.method(
          #generateSecureKey,
          [],
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i12.Future<bool> boxExists(
    String? name, {
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #boxExists,
          [name],
          {#path: path},
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  void resetAdapters() => super.noSuchMethod(
        Invocation.method(
          #resetAdapters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerAdapter<T>(
    _i10.TypeAdapter<T>? adapter, {
    bool? internal = false,
    bool? override = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerAdapter,
          [adapter],
          {
            #internal: internal,
            #override: override,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isAdapterRegistered(int? typeId) => (super.noSuchMethod(
        Invocation.method(
          #isAdapterRegistered,
          [typeId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void ignoreTypeId<T>(int? typeId) => super.noSuchMethod(
        Invocation.method(
          #ignoreTypeId,
          [typeId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i11.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i11.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<_i11.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i12.Future<_i11.Response>);

  @override
  _i12.Future<_i11.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<_i11.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i12.Future<_i11.Response>);

  @override
  _i12.Future<_i11.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i11.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i11.Response>);

  @override
  _i12.Future<_i11.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i11.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i11.Response>);

  @override
  _i12.Future<_i11.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i11.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i11.Response>);

  @override
  _i12.Future<_i11.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i11.Response>.value(_FakeResponse_11(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i11.Response>);

  @override
  _i12.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<_i24.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<_i24.Uint8List>.value(_i24.Uint8List(0)),
      ) as _i12.Future<_i24.Uint8List>);

  @override
  _i12.Future<_i11.StreamedResponse> send(_i11.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i12.Future<_i11.StreamedResponse>.value(_FakeStreamedResponse_12(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i12.Future<_i11.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
